name: smart_franchise_pos
description: Point Of Sale for Franchise to become Smart.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  input_quantity: ^2.2.0
  image_picker: ^1.0.5
  dio: ^5.4.0
  intl: ^0.19.0
  file_picker: ^6.1.1
  shortid: ^0.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
